### ISSUE TITLE
Deep linking of questions

### ISSUE THREAD

**Issue by hugomarcotte** [hugomarcotte/FUIR_Web#1]
- The main controller contains logic to load the right question if there is a qId parameter in the URL. 
- openQuestionCard takes care of changing the qId in the URL when a question is opened by the user clicking.
- On locationChangeSuccess loads the right question based on the qId parameter.

Would like to get your opinion on the implementation.

Thanks

**Comment by davidyang** [comment]
Hey Hugo - this looks fine though it's not the standard way to do it.  

You can have two states in the router (https://github.com/hugomarcotte/FUIR_Web/blob/master/client/app/main/main.js):

main
main.showQuestion

and have the showQuestion state use the qId, then you don't have to have all the conditional logic in the main controller about the qId.  We can discuss further in person.
